### PR TITLE
Support dynamic segments and queryParams

### PR DESCRIPTION
**Pull request by misterbyrne**
It wasn't working properly for dynamic segments, so I've changed it so the URL is stashed instead of the route path. I've noticed that this also makes it work for queryParams so I added a test for both scenarios.

### CODE REVIEW

**Comment by jelhan** [comment]
Thanks for your work! Looks good. Fixed the tests in #10. Could you please rebase?

**Comment by barryofguilder** [comment]
Any way this PR could get updated and merged? This was exactly what I needed.

**Comment by jelhan** [comment]
I'm sorry that this pull request has been open for such a long time. Tests were failing for ember 2.12 only. This shouldn't have been an issue. Merged after upgrading this addon to latest ember in #12, which has fixed the tests by dropping support for ember 2.12.

**Comment by barryofguilder** [comment]
@jelhan thanks for merging! And thanks for creating this test helper. This worked perfectly for me today on my project!

**Comment by misterbyrne** [comment]
Hey, thanks for following up - Sorry for abandoning this PR! (I don't remember why :) )

**Pull request merged**
